name: Build Debian Camera Servers Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  build_and_pack_pi:
    name: Build and Package Camera Servers for Pi
    runs-on: Pi4

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build debian package
      env:
        DEBEMAIL: james@viam.com
        DEBFULLNAME: Viam Buildbot/James Otting
      run: |
        make deb

    - name: Add package to repo
      run: |
        dput local packaging/debian/work/*.changes

    - name: Sync repo to cloud
      run: |
        gsutil -m rsync -d -r /home/buildbot/debian/viam gs://packages.viam.com/debian/viam
        gsutil -m setmeta -h "Cache-Control: no-cache" 'gs://packages.viam.com/debian/viam/[A-Z]*'
